#!/usr/bin/env python3

from gnucash_uk_accounts.config import Config
from gnucash_uk_accounts.worksheet import get_worksheet
import gnucash_uk_accounts.accounts as accounts
import sys

from gnucash_uk_accounts.element import get_element

if len(sys.argv) < 4:
    sys.stderr.write("Usage:\n    report <config> <report> <format>\n")
    sys.exit(1)

cfg = Config.load(sys.argv[1])

file = cfg.get("accounts.file")

session = accounts.Accounts(file)

elt = get_element(sys.argv[2], cfg, session)

if sys.argv[3] == "ixbrl":
    elt.to_ixbrl(sys.stdout)
elif sys.argv[3] == "html":
    elt.to_html(sys.stdout)
elif sys.argv[3] == "text":
    elt.to_text(sys.stdout)
else:
    raise RuntimeError("Output type '%s' not known." % sys.argv[3])

