#!/usr/bin/env python3

from gnucash_uk_reports.config import Config
from gnucash_uk_reports.worksheet import get_worksheet
import gnucash_uk_reports.accounts as accounts
from gnucash_uk_reports.fact import FRS101
import sys

from gnucash_uk_reports.element import get_element

if len(sys.argv) < 4:
    sys.stderr.write("Usage:\n    report <config> <report> <format>\n")
    sys.exit(1)

cfg = Config.load(sys.argv[1])

tx_cfg = Config.load("taxonomy.json")

file = cfg.get("accounts.file")

session = accounts.Accounts(file)

tx = FRS101(tx_cfg)

elt = get_element(sys.argv[2], cfg, session, tx)

if sys.argv[3] == "ixbrl":
    elt.to_ixbrl(sys.stdout)
elif sys.argv[3] == "html":
    elt.to_html(sys.stdout)
elif sys.argv[3] == "text":
    elt.to_text(sys.stdout)
else:
    raise RuntimeError("Output type '%s' not known." % sys.argv[3])

