#!/usr/bin/env python3

from gnucash_uk_reports.config import Config

import gnucash_uk_reports.accounts as accounts
from gnucash_uk_reports.taxonomy import FRS101
import sys
from gnucash_uk_reports.datasource import DataSource

if len(sys.argv) < 4:
    sys.stderr.write("Usage:\n    report <config> <report> <format>\n")
    sys.exit(1)

cfg = Config.load(sys.argv[1])

tx_cfg = Config.load("taxonomy.json")

file = cfg.get("accounts.file")

session = accounts.Accounts(file)

d = DataSource(cfg, session)

elt = d.get_element(sys.argv[2])

if sys.argv[3] == "ixbrl":
    tx = FRS101(tx_cfg)
    elt.to_ixbrl(tx, sys.stdout)
elif sys.argv[3] == "html":
    elt.to_html(sys.stdout)
elif sys.argv[3] == "text":
    elt.to_text(sys.stdout)
else:
    raise RuntimeError("Output type '%s' not known." % sys.argv[3])

